apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-pipeline-outputs
  namespace: {{ include "pdf-pipeline.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.outputs.storageClassName }}
  storageClassName: {{ .Values.persistence.outputs.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.outputs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-pipeline-db
  namespace: {{ include "pdf-pipeline.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.db.storageClassName }}
  storageClassName: {{ .Values.persistence.db.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
