# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      no_proxy: ${no_proxy}
      # MONGO_INITDB_ROOT_USERNAME: agents
      # MONGO_INITDB_ROOT_PASSWORD: agents
    restart: unless-stopped
  
  # groq-service:
  #   image: thebeginner86intel/ai-agents-groq:latest
  #   container_name: groq-service
  #   ports:
  #     - "5099:8000"
  #   volumes:
  #     - "./cache:/root/.cache"
  #   environment:
  #     no_proxy: ${no_proxy}
  #     http_proxy: ${http_proxy}
  #     https_proxy: ${https_proxy}
  #     GROQ_API_KEY: ${GROQ_API_KEY}
  #     HTTP_PROXY: ${HTTP_PROXY}
  #     HTTPS_PROXY: ${HTTPS_PROXY}

  backend:
    image: navchetna/tender-eval-backend:latest
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      - no_proxy=${no_proxy}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ipc: host
    restart: always
  
  ui:
    image: navchetna/tender-eval-ui:latest
    depends_on:
      - backend
    ports:
      - "5009:4173"
    environment:
      - no_proxy=${no_proxy}
    restart: always

networks:
  default:
    driver: bridge